// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SovosProjectTest.Infrastructure.Data;

#nullable disable

namespace SovosProjectTest.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241126212254_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SovosProjectTest.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f736b7d9-f66c-4ac8-82fc-ee2efd84c8b1"),
                            Category = "Category 1",
                            Name = "Product A",
                            Price = 10.0m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("3a5d732e-cdc8-4bad-9de4-ae9473709386"),
                            Category = "Category 2",
                            Name = "Product B",
                            Price = 20.0m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = new Guid("2436f658-bee1-4d93-87e4-aae17eb10962"),
                            Category = "Category 1",
                            Name = "Product C",
                            Price = 30.0m,
                            StockQuantity = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
